version: '3.8'

services:
  logger-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logger-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://guest:guest@host.docker.internal:5672
      - RABBITMQ_EXCHANGE=data_service_events
      - RABBITMQ_QUEUE=data_service_logs
      - RABBITMQ_ROUTING_KEY_PATTERN=data.service.#
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - logger-network

volumes:
  node_modules:

networks:
  logger-network:
    driver: bridge
